"use client";

import { useState, useEffect, use } from "react";
import { useRouter } from "next/navigation";
import { getGeneratedSQL } from "@/lib/api";

export default function SQLPage({ params }: { params: Promise<{ jobId: string }> }) {
  const { jobId } = use(params);
  const router = useRouter();
  const [sql, setSQL] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    getGeneratedSQL(jobId)
      .then((data) => setSQL(data.sql))
      .finally(() => setLoading(false));
  }, [jobId]);

  const handleCopy = () => {
    if (sql) {
      navigator.clipboard.writeText(sql);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  if (loading) return <div className="text-center py-12 text-visa-gray-500">Loading SQL query...</div>;
  if (!sql) return <div className="text-center py-12 text-visa-gray-500">SQL query not yet generated</div>;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-visa-navy">Generated Aggregation Query</h2>
          <p className="text-sm text-visa-gray-500">DuckDB SQL that transforms raw data into AMMF format</p>
        </div>
        <div className="flex gap-2">
          <button onClick={handleCopy}
            className="px-4 py-2 text-sm bg-visa-gold text-visa-navy rounded-lg font-medium hover:opacity-90">
            {copied ? "Copied!" : "Copy SQL"}
          </button>
          <button onClick={() => router.push(`/pipeline/${jobId}`)}
            className="px-4 py-2 text-sm bg-visa-gray-100 text-visa-gray-700 rounded-lg hover:bg-visa-gray-200">
            Back to Dashboard
          </button>
        </div>
      </div>

      <div className="bg-visa-gray-900 rounded-lg p-6 overflow-x-auto">
        <pre className="text-sm text-green-400 font-mono whitespace-pre-wrap leading-relaxed">{sql}</pre>
      </div>

      <div className="bg-white rounded-lg shadow-sm border border-visa-gray-200 p-4">
        <h3 className="font-semibold text-visa-navy mb-2">About this query</h3>
        <ul className="text-sm text-visa-gray-500 space-y-1">
          <li>- Generated by Claude AI based on schema mapping and relationship discovery</li>
          <li>- Produces exactly 31 AMMF columns with correct naming</li>
          <li>- Uses LEFT JOINs for optional tables and COALESCE for null handling</li>
          <li>- Validated via trial execution with up to 3 retry attempts</li>
        </ul>
      </div>
    </div>
  );
}
